<div class="page-header">
    <h1>Time-tracking</h1>
</div>

<br/>
<form method="post" action="<?php echo App::config('url') ?>form/update" enctype="multipart/form-data">

    <div class="form-group">
        <label for="zaposlenik">Zaposlenik</label>
        <input id="zaposlenik" name="zaposlenik" required class="form-control" value="<?php echo $data['zaposlenik'] ?>" />
    </div>
    <div class="form-group">
        <label for="iznos">Broj sati</label>
        <input id="iznos" name="iznos" required class="form-control" value="<?php echo $data['iznos'] ?>"/>
    </div>

    <div class="form-group">
        <label for="opis">Opis</label>
        <textarea id="opis" name="opis" placeholder="Opis..." required class="form-control" ><?php echo $data['opis'] ?></textarea>
    </div>

    <div class="form-group">
        <label>Datum</label>
        <input id="datum" name="datum" type="date" required class="form-control" value="<?php echo $data['datum'] ?>"/>
    </div>

    <div class="form-group">
        <label>Vrsta posla</label><br />
        <select name="vrsta">
        <?php foreach(array('Design', 'Development', 'Support') as $key => $vrsta): ?>
            <option value="<?php echo $vrsta ?>"<?php if ($vrsta == $data['vrsta']){echo 'selected';}?>><?php echo $vrsta ?></option>
        <?php endforeach ?>
        </select>
     </div>

    <br/>
    <input type="hidden" name="id" value="<?php echo $data['id'] ?>" >
    <button type="submit" class="btn btn-primary">Izmjeni</button>

</form>