<div class="page-header">
    <h1>Time-tracking</h1>
</div>

<br/>

<form method="post" action="<?php echo App::config('url') ?>form/submit" enctype="multipart/form-data">

    <div class="form-group">
        <label for="zaposlenik">Zaposlenik</label>
        <input id="zaposlenik" name="zaposlenik" required class="form-control" />
    </div>
    <div class="form-group">
        <label for="iznos">Broj sati</label>
        <input id="iznos" name="iznos" required class="form-control" />
    </div>

    <div class="form-group">
        <label for="opis">Opis</label>
        <textarea id="opis" name="opis" placeholder="Opis..." required class="form-control" ></textarea>
    </div>

    <div class="form-group">
        <label>Datum</label>
        <input id="datum" name="datum" type="date" required class="form-control" />
    </div>

    <div class="form-group">
        <label>Vrsta posla</label><br />
        <select name="vrsta">
        <?php foreach(array('Design', 'Development', 'Support') as $key => $task): ?>
            <option value="<?php echo $task ?>"><?php echo $task ?></option>
        <?php endforeach ?>
        </select>
     </div>

    <br/>

    <button type="submit" class="btn btn-primary">Unesi</button>

</form>